sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON=python3.8
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip
  - unzip -qq google-cloud-sdk.zip
  - export CLOUDSDK_PYTHON=python3.8 # or any Python version >= 3.8 installed on the image
  - ./google-cloud-sdk/install.sh  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project named-dialect-404616
  - gcloud config set compute/zone europe-west6-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t roeezach/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true roeezach/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
