sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - sudo rm -rf /opt/pyenv # Remove existing pyenv installation
  - curl https://pyenv.run | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init --path)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 3.8.13
  - pyenv global 3.8.13
  - python --version
  - curl https://sdk.cloud.google.com | CLOUDSDK_PYTHON=python3.8 bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - export PATH=$PATH:$HOME/google-cloud-sdk/bin
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project named-dialect-404616
  - gcloud config set compute/zone europe-west6-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t roeezach/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true roeezach/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
